name: Validate Generated PDF/PNG # fails if the commited PDF/PNG is not up to date

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build new PNG
        run: make png

      - name: Fail if PNG is not up to date
        run: git diff --exit-code -a generated/resume-*.png
